### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by PandaGab** [aldro61/pyscm#58]
Hello,
In a fresh python environnement (3.11.5), I can't install the package using `python -m pip install pyscm-ml`. I get the following error:
<details>
  <summary>pip install pyscm-ml <i>logs</i></summary>

  ````text
  python -m pip install pyscm-ml
  Collecting pyscm-ml
    Using cached pyscm-ml-1.0.3.tar.gz (13 kB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... error
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [20 lines of output]
        Traceback (most recent call last):
          File "/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File ".venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "/private/var/folders/jb/650l4dw15nx4gczf01rdg4xh0000gn/T/pip-build-env-9w7hy0tr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=[])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/private/var/folders/jb/650l4dw15nx4gczf01rdg4xh0000gn/T/pip-build-env-9w7hy0tr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
            self.run_setup()
          File "/private/var/folders/jb/650l4dw15nx4gczf01rdg4xh0000gn/T/pip-build-env-9w7hy0tr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 503, in run_setup
            super().run_setup(setup_script=setup_script)
          File "/private/var/folders/jb/650l4dw15nx4gczf01rdg4xh0000gn/T/pip-build-env-9w7hy0tr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
            exec(code, locals())
          File "<string>", line 19, in <module>
        ModuleNotFoundError: No module named 'numpy'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  ````
</details>

I also get an error when installing locally after cloning the project. Using the command provided from the README `python setup.py install`:

<details>
  <summary>python setup.py install <i>logs</i></summary>

  ````text
  /pyscm/.venv/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
running install
/pyscm/.venv/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/pyscm/.venv/lib/python3.11/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing pyscm_ml.egg-info/PKG-INFO
writing dependency_links to pyscm_ml.egg-info/dependency_links.txt
writing requirements to pyscm_ml.egg-info/requires.txt
writing top-level names to pyscm_ml.egg-info/top_level.txt
reading manifest file 'pyscm_ml.egg-info/SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'pyscm_ml.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-14.0-arm64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-14.0-arm64-cpython-311
creating build/lib.macosx-14.0-arm64-cpython-311/pyscm
copying pyscm/__init__.py -> build/lib.macosx-14.0-arm64-cpython-311/pyscm
copying pyscm/rules.py -> build/lib.macosx-14.0-arm64-cpython-311/pyscm
copying pyscm/model.py -> build/lib.macosx-14.0-arm64-cpython-311/pyscm
copying pyscm/utils.py -> build/lib.macosx-14.0-arm64-cpython-311/pyscm
copying pyscm/scm.py -> build/lib.macosx-14.0-arm64-cpython-311/pyscm
creating build/lib.macosx-14.0-arm64-cpython-311/pyscm/tests
copying pyscm/tests/test_sklearn_compatibility.py -> build/lib.macosx-14.0-arm64-cpython-311/pyscm/tests
copying pyscm/tests/__init__.py -> build/lib.macosx-14.0-arm64-cpython-311/pyscm/tests
copying pyscm/tests/test_utility.py -> build/lib.macosx-14.0-arm64-cpython-311/pyscm/tests
running build_ext
building 'pyscm._scm_utility' extension
creating build/temp.macosx-14.0-arm64-cpython-311
creating build/temp.macosx-14.0-arm64-cpython-311/cpp_extensions
clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/pyscm/.venv/include -I/.pyenv/versions/3.11.5/include/python3.11 -I/pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include -c cpp_extensions/solver.cpp -o build/temp.macosx-14.0-arm64-cpython-311/cpp_extensions/solver.o -std=c++0x -mmacosx-version-min=10.9
clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/pyscm/.venv/include -I/.pyenv/versions/3.11.5/include/python3.11 -I/pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include -c cpp_extensions/utility_python_bindings.cpp -o build/temp.macosx-14.0-arm64-cpython-311/cpp_extensions/utility_python_bindings.o -std=c++0x -mmacosx-version-min=10.9
In file included from cpp_extensions/utility_python_bindings.cpp:2:
In file included from /pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include/numpy/arrayobject.h:5:
In file included from /pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include/numpy/ndarrayobject.h:12:
In file included from /pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include/numpy/ndarraytypes.h:1909:
/pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
cpp_extensions/utility_python_bindings.cpp:28:27: error: use of undeclared identifier 'PyArray_DOUBLE'
    if(PyArray_TYPE(X) != PyArray_DOUBLE){
                          ^
cpp_extensions/utility_python_bindings.cpp:33:27: error: use of undeclared identifier 'PyArray_LONG'
    if(PyArray_TYPE(y) != PyArray_LONG){
                          ^
cpp_extensions/utility_python_bindings.cpp:38:46: error: use of undeclared identifier 'PyArray_LONG'
    if(PyArray_TYPE(X_argsort_by_feature) != PyArray_LONG){
                                             ^
cpp_extensions/utility_python_bindings.cpp:43:37: error: use of undeclared identifier 'PyArray_LONG'
    if(PyArray_TYPE(example_idx) != PyArray_LONG){
                                    ^
cpp_extensions/utility_python_bindings.cpp:48:60: error: use of undeclared identifier 'PyArray_DOUBLE'
    if(feature_weights && PyArray_TYPE(feature_weights) != PyArray_DOUBLE){
                                                           ^
cpp_extensions/utility_python_bindings.cpp:146:58: error: use of undeclared identifier 'PyArray_LONG'
    PyObject *opti_feat_idx = PyArray_SimpleNew(1, dims, PyArray_LONG);
                                                         ^
cpp_extensions/utility_python_bindings.cpp:147:39: error: no matching function for call to 'PyArray_DATA'
    long *opti_feat_idx_data = (long*)PyArray_DATA(opti_feat_idx);
                                      ^~~~~~~~~~~~
/pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include/numpy/ndarraytypes.h:1508:1: note: candidate function not viable: no known conversion from 'PyObject *' (aka '_object *') to 'const PyArrayObject *' (aka 'const tagPyArrayObject_fields *') for 1st argument
PyArray_DATA(const PyArrayObject *arr)
^
cpp_extensions/utility_python_bindings.cpp:149:60: error: use of undeclared identifier 'PyArray_DOUBLE'
    PyObject *opti_thresholds = PyArray_SimpleNew(1, dims, PyArray_DOUBLE);
                                                           ^
cpp_extensions/utility_python_bindings.cpp:150:45: error: no matching function for call to 'PyArray_DATA'
    double *opti_thresholds_data = (double*)PyArray_DATA(opti_thresholds);
                                            ^~~~~~~~~~~~
/pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include/numpy/ndarraytypes.h:1508:1: note: candidate function not viable: no known conversion from 'PyObject *' (aka '_object *') to 'const PyArrayObject *' (aka 'const tagPyArrayObject_fields *') for 1st argument
PyArray_DATA(const PyArrayObject *arr)
^
cpp_extensions/utility_python_bindings.cpp:152:55: error: use of undeclared identifier 'PyArray_LONG'
    PyObject *opti_kinds = PyArray_SimpleNew(1, dims, PyArray_LONG);
                                                      ^
cpp_extensions/utility_python_bindings.cpp:153:36: error: no matching function for call to 'PyArray_DATA'
    long *opti_kinds_data = (long*)PyArray_DATA(opti_kinds);
                                   ^~~~~~~~~~~~
/pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include/numpy/ndarraytypes.h:1508:1: note: candidate function not viable: no known conversion from 'PyObject *' (aka '_object *') to 'const PyArrayObject *' (aka 'const tagPyArrayObject_fields *') for 1st argument
PyArray_DATA(const PyArrayObject *arr)
^
cpp_extensions/utility_python_bindings.cpp:155:51: error: use of undeclared identifier 'PyArray_LONG'
    PyObject *opti_N = PyArray_SimpleNew(1, dims, PyArray_LONG);
                                                  ^
cpp_extensions/utility_python_bindings.cpp:156:32: error: no matching function for call to 'PyArray_DATA'
    long *opti_N_data = (long*)PyArray_DATA(opti_N);
                               ^~~~~~~~~~~~
/pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include/numpy/ndarraytypes.h:1508:1: note: candidate function not viable: no known conversion from 'PyObject *' (aka '_object *') to 'const PyArrayObject *' (aka 'const tagPyArrayObject_fields *') for 1st argument
PyArray_DATA(const PyArrayObject *arr)
^
cpp_extensions/utility_python_bindings.cpp:158:55: error: use of undeclared identifier 'PyArray_LONG'
    PyObject *opti_P_bar = PyArray_SimpleNew(1, dims, PyArray_LONG);
                                                      ^
cpp_extensions/utility_python_bindings.cpp:159:36: error: no matching function for call to 'PyArray_DATA'
    long *opti_P_bar_data = (long*)PyArray_DATA(opti_P_bar);
                                   ^~~~~~~~~~~~
/pyscm/.eggs/numpy-2.1.1-py3.11-macosx-14.0-arm64.egg/numpy/_core/include/numpy/ndarraytypes.h:1508:1: note: candidate function not viable: no known conversion from 'PyObject *' (aka '_object *') to 'const PyArrayObject *' (aka 'const tagPyArrayObject_fields *') for 1st argument
PyArray_DATA(const PyArrayObject *arr)
^
1 warning and 15 errors generated.
error: command '/usr/bin/clang' failed with exit code 1
  ````
</details>

Thank you for your help.

**Comment by thibgo** [comment]
@PandaGab the package have been updated since. It may have solve the problem. You can try again with `pip install pyscm-ml`. If you still get an error let us know. Sorry for the late answer!

**Comment by PandaGab** [comment]
Indeed, it works now. Thank you !
